export const FETCH_VIDEO_HIGHLIGHTS = "FETCH_VIDEO_HIGHLIGHTS"; //COMEDY VIDEOS
export const FETCH_NEWS_BITS = "FETCH_NEWS_BITS"; //LOCAL NEWS
export const FETCH_SIDE_ADS = "FETCH_SIDE_ADS";

export const FETCH_SEEDOOTV_ENTERTAINMENT_NEWS = "FETCH_SEEDOOTV_ENTERTAINMENT_NEWS";
export const FETCH_SEEDOOTV_AFRICAN_NEWS = "FETCH_SEEDOOTV_AFRICAN_NEWS";
export const FETCH_SEEDOOTV_HUMAN_NEWS = "FETCH_SEEDOOTV_HUMAN_NEWS";

export const FETCH_SEEDOOTV_KIDDIES_VIDEOS = "FETCH_SEEDOOTV_KIDDIES_VIDEOS";
export const FETCH_SEEDOOTV_MUSIC_VIDEOS = "FETCH_SEEDOOTV_MUSIC_VIDEOS";
export const FETCH_SEEDOOTV_MOVIES_VIDEOS = "FETCH_SEEDOOTV_MOVIES_VIDEOS";