export const FETCH_VIDEO_HIGHLIGHTS = "FETCH_VIDEO_HIGHLIGHTS";
export const FETCH_NEWS_BITS = "FETCH_NEWS_BITS";
export const FETCH_SIDE_ADS = "FETCH_SIDE_ADS";

export const FETCH_SEEDOOTV_NEWS = "FETCH_SEEDOOTV_NEWS"